# Generated by Django 4.1.7 on 2023-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLRedirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(max_length=50, null=True)),
                ('shortURL', models.URLField(null=True)),
                ('longURL', models.URLField(null=True)),
            ],
        ),
    ]
